### ISSUE TITLE
meta kik-icon ignored if on a different protocol

### ISSUE THREAD

**Issue by austinhallock** [kikinteractive/kik-js-issues#12]
Kik seems to ignore the kik-icon if an https icon is specified from an http page.

Eg. if on http://battlefish.clay.io we specify https://cdn.wtf/g/2882/icon_1422255596471.png as an icon, Kik doesn't use it (shows the black globe thing). If http://cdn.wtf/g/2882/icon_1422255596471.png is specified, it works as intended.

**Comment by Zolmeister** [comment]
Any updates on this?

**Comment by jairajs89** [comment]
This issue will be resolved in the next version of Kik

**Comment by austinhallock** [comment]
Great, thanks!
