### ISSUE TITLE
window.open override parameters

### ISSUE THREAD

**Issue by Zolmeister** [kikinteractive/kik-js-issues#13]
kik.js overrides `window.open` (which it should not do, but I'll assume you have a good reason for it),
but when called does not pass arguments, and causes `window.open` to  replace the current page instead of opening in a new window.

The issue is that this happens outside of Kik, so any application available externally which includes kik.js is affected.

Workaround:

```html
<script>oldOpen = window.open</script>
<script src="//cdn.kik.com/kik/1.0.18/kik.js"></script>
<script>window.open = oldOpen</script>
```

**Comment by jairajs89** [comment]
Yup, we're already working on a solution for this. It was required for specific use-cases inside Kik Browser. Kik Browser does not have a concept for "tabs" so `window.open()` could never open a new window -- this is why we had to override it to get desired behaviour.

A fix should be out in the near future
