### ISSUE TITLE
Blank page on android 4.x

### ISSUE THREAD

**Issue by amalyuhin** [kikinteractive/kik-js-issues#14]
I used official code example of Ionic framework http://codepen.io/ionic/pen/XJVRQj for tab navigation. It works fine in kik application. Then I include script http://cdn.kik.com/kik/1.0.18/kik.js and sometimes it breakes. Although it works fine for android 5.0.
The issue appears not only with Ionic framework, but also with Onsen UI framework. Code example is here http://codepen.io/onsen/pen/pGuDL.
Please advise.

**Comment by jairajs89** [comment]
This is due to the restrictive navigation environment for webapps that use Kik APIs. These restrictions will soon be lifted in a coming release

**Comment by amalyuhin** [comment]
@jairajs89 Thank you for your reply. Could you please say when you plan this release ?

**Comment by jairajs89** [comment]
Sometime over the next month
