### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by dmitry-nosov** [kikinteractive/kik-js-issues#15]
Hi, the KIK API does not seem to give push tokens anymore (it returns empty tokens). The notifications are sent with the status 200 but are not received by application users. Is it a bug or some radical change in how apps can interact with users?

**Comment by dmitry-nosov** [comment]
Jairaj, I would be grateful for any updates!

**Comment by jairajs89** [comment]
The Push Notification Service was deprecated in the last version of Kik (8.2). Over the last year we have migrated client to using Official Accounts within Kik for a much better notification experience. The benefits are that the UI is native to the chat experience while using the OS-native notification services.

**Comment by dmitry-nosov** [comment]
Thanks for you answer, but unfortunately it did not help me much as I do not understand what alternatives have KIK apps to notify users of updates. What do you mean by Official Accounts? For example, we have a new game, how can we quickly notify all our registered users about it?

**Comment by jairajs89** [comment]
If you would like to get setup with an Official Account send an email to partners@kik.com to get the process started
